// <auto-generated />
using System;
using EnergisaNotes.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergisaNotes.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211222815_AjusteCamposColaborador")]
    partial class AjusteCamposColaborador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9057),
                            Nome = "Corporativo"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9065),
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9065),
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9066),
                            Nome = "Operações"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9067),
                            Nome = "Comercial"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9067),
                            Nome = "Atendimento"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cargos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9531),
                            Nome = "Colaborador"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9532),
                            Nome = "Analista de T.I."
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9533),
                            Nome = "Gerente"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9534),
                            Nome = "Eletricista"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9535),
                            Nome = "Atendente"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 875, DateTimeKind.Utc).AddTicks(9535),
                            Nome = "Supervisor"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(167),
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(168),
                            Nome = "Infraestrutura Predial"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(169),
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(169),
                            Nome = "Segurança do Trabalho"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(170),
                            Nome = "Operações de Rede"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(171),
                            Nome = "Frota e Logística"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aniversario")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Empresa")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Colaboradores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aniversario = "01/01",
                            AreaId = 1,
                            CargoId = 3,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(3932),
                            Email = "admin@energisa.com.br",
                            Empresa = "Energisa Participações",
                            Endereco = "Rua da Matriz, 100",
                            Nome = "Admin Energisa"
                        },
                        new
                        {
                            Id = 2,
                            Aniversario = "15/05",
                            AreaId = 6,
                            CargoId = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(3935),
                            Email = "joao.silva@energisa.com.br",
                            Empresa = "Energisa Mato Grosso",
                            Endereco = "Av. Historiador Rubens de Mendonça, 200",
                            Nome = "João Colaborador"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TextoTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UltimoEditorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UltimoEditorId");

                    b.ToTable("Incidentes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(9404),
                            TextoTemplate = "Prezados, informamos que a unidade [Unidade] encontra-se sem acesso à internet...",
                            Titulo = "Indisponibilidade de Link (Internet)",
                            UltimoEditorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(9406),
                            TextoTemplate = "Identificamos lentidão no módulo [ModuloSAP] do sistema SAP...",
                            Titulo = "Lentidão no SAP",
                            UltimoEditorId = 1
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CargoId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AzureAdObjectId")
                        .IsUnique();

                    b.HasIndex("CargoId");

                    b.HasIndex("ColaboradorId")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000001",
                            ColaboradorId = 1,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(6106),
                            IsSupervisor = true
                        },
                        new
                        {
                            Id = 2,
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000002",
                            ColaboradorId = 2,
                            DataCriacao = new DateTime(2025, 12, 11, 22, 28, 14, 876, DateTimeKind.Utc).AddTicks(6109),
                            IsSupervisor = false
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergisaNotes.Domain.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergisaNotes.Domain.Entities.Usuario", "UltimoEditor")
                        .WithMany()
                        .HasForeignKey("UltimoEditorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("UltimoEditor");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Area", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId");

                    b.HasOne("EnergisaNotes.Domain.Entities.Cargo", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId");

                    b.HasOne("EnergisaNotes.Domain.Entities.Colaborador", "Colaborador")
                        .WithOne("Usuario")
                        .HasForeignKey("EnergisaNotes.Domain.Entities.Usuario", "ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Area", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Colaborador", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
