// <auto-generated />
using System;
using EnergisaNotes.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergisaNotes.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205184302_SeedDataV2")]
    partial class SeedDataV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(617),
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(620),
                            Nome = "Infraestrutura Predial"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(621),
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(622),
                            Nome = "Segurança do Trabalho"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(623),
                            Nome = "Operações de Rede"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(624),
                            Nome = "Frota e Logística"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TextoTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UltimoEditorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UltimoEditorId");

                    b.ToTable("Incidentes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(695),
                            TextoTemplate = "Prezados, informamos que a unidade [Unidade] encontra-se sem acesso à internet devido a uma falha massiva na operadora. A previsão de retorno é para as [Horario]. Equipe de T.I.",
                            Titulo = "Indisponibilidade de Link (Internet)",
                            UltimoEditorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(697),
                            TextoTemplate = "Identificamos lentidão no módulo [ModuloSAP] do sistema SAP. O time de sustentação já está atuando. Chamado técnico: [NumeroChamado].",
                            Titulo = "Lentidão no SAP",
                            UltimoEditorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(698),
                            TextoTemplate = "Atenção colaboradores do setor [Setor]. Haverá manutenção preventiva nos aparelhos de ar condicionado no dia [Data] entre [HoraInicio] e [HoraFim].",
                            Titulo = "Manutenção Ar Condicionado",
                            UltimoEditorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(699),
                            TextoTemplate = "Informamos que o sistema de ponto apresenta instabilidade hoje, dia [Data]. Favor registrar o ponto manualmente via formulário entregue pelo gestor [NomeGestor].",
                            Titulo = "Erro no Ponto Eletrônico",
                            UltimoEditorId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(700),
                            TextoTemplate = "Alerta para as equipes de campo da região [Regiao]: Previsão de tempestades severas para as próximas [Horas] horas. Redobrem a atenção e sigam o protocolo de segurança [Protocolo].",
                            Titulo = "Alerta de Chuvas Fortes",
                            UltimoEditorId = 1
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasColumnType("longtext");

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TelefonePessoal")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AzureAdObjectId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Corporativo",
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000001",
                            Cargo = "Gerente de T.I.",
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(675),
                            Email = "admin@energisa.com.br",
                            IsSupervisor = true,
                            Nome = "Admin Energisa"
                        },
                        new
                        {
                            Id = 2,
                            Area = "Atendimento",
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000002",
                            Cargo = "Analista Jr",
                            DataCriacao = new DateTime(2025, 12, 5, 18, 43, 1, 848, DateTimeKind.Utc).AddTicks(676),
                            Email = "joao.silva@energisa.com.br",
                            IsSupervisor = false,
                            Nome = "João Colaborador"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergisaNotes.Domain.Entities.Usuario", "UltimoEditor")
                        .WithMany()
                        .HasForeignKey("UltimoEditorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("UltimoEditor");
                });
#pragma warning restore 612, 618
        }
    }
}
