// <auto-generated />
using System;
using EnergisaNotes.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergisaNotes.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210004635_AdicionandoCargosAgain")]
    partial class AdicionandoCargosAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(5596),
                            Nome = "Corporativo"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(5600),
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(5601),
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(5602),
                            Nome = "Operações"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(5603),
                            Nome = "Comercial"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(5604),
                            Nome = "Atendimento"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cargos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(6166),
                            Nome = "Colaborador"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(6167),
                            Nome = "Analista de T.I."
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(6168),
                            Nome = "Gerente"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(6169),
                            Nome = "Eletricista"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(6169),
                            Nome = "Atendente"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 242, DateTimeKind.Utc).AddTicks(6170),
                            Nome = "Supervisor"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5777),
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5784),
                            Nome = "Infraestrutura Predial"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5785),
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5785),
                            Nome = "Segurança do Trabalho"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5786),
                            Nome = "Operações de Rede"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5787),
                            Nome = "Frota e Logística"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TextoTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UltimoEditorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UltimoEditorId");

                    b.ToTable("Incidentes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5863),
                            TextoTemplate = "Prezados, informamos que a unidade [Unidade] encontra-se sem acesso à internet...",
                            Titulo = "Indisponibilidade de Link (Internet)",
                            UltimoEditorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5865),
                            TextoTemplate = "Identificamos lentidão no módulo [ModuloSAP] do sistema SAP...",
                            Titulo = "Lentidão no SAP",
                            UltimoEditorId = 1
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TelefonePessoal")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AzureAdObjectId")
                        .IsUnique();

                    b.HasIndex("CargoId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000001",
                            CargoId = 3,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5839),
                            Email = "admin@energisa.com.br",
                            IsSupervisor = true,
                            Nome = "Admin Energisa"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 6,
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000002",
                            CargoId = 2,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 46, 35, 243, DateTimeKind.Utc).AddTicks(5842),
                            Email = "joao.silva@energisa.com.br",
                            IsSupervisor = false,
                            Nome = "João Colaborador"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergisaNotes.Domain.Entities.Usuario", "UltimoEditor")
                        .WithMany()
                        .HasForeignKey("UltimoEditorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("UltimoEditor");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergisaNotes.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Area", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
