// <auto-generated />
using System;
using EnergisaNotes.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergisaNotes.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210004231_AdicionandoCargos")]
    partial class AdicionandoCargos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Areas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(1395),
                            Nome = "Corporativo"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(1399),
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(1400),
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(1401),
                            Nome = "Operações"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(1402),
                            Nome = "Comercial"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(1402),
                            Nome = "Atendimento"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8478),
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8481),
                            Nome = "Infraestrutura Predial"
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8481),
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8482),
                            Nome = "Segurança do Trabalho"
                        },
                        new
                        {
                            Id = 5,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8483),
                            Nome = "Operações de Rede"
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8483),
                            Nome = "Frota e Logística"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TextoTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UltimoEditorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UltimoEditorId");

                    b.ToTable("Incidentes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8541),
                            TextoTemplate = "Prezados, informamos que a unidade [Unidade] encontra-se sem acesso à internet...",
                            Titulo = "Indisponibilidade de Link (Internet)",
                            UltimoEditorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8542),
                            TextoTemplate = "Identificamos lentidão no módulo [ModuloSAP] do sistema SAP...",
                            Titulo = "Lentidão no SAP",
                            UltimoEditorId = 1
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("TelefonePessoal")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AzureAdObjectId")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000001",
                            Cargo = "Gerente de T.I.",
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8518),
                            Email = "admin@energisa.com.br",
                            IsSupervisor = true,
                            Nome = "Admin Energisa"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 6,
                            AzureAdObjectId = "00000000-0000-0000-0000-000000000002",
                            Cargo = "Analista Jr",
                            DataCriacao = new DateTime(2025, 12, 10, 0, 42, 31, 74, DateTimeKind.Utc).AddTicks(8520),
                            Email = "joao.silva@energisa.com.br",
                            IsSupervisor = false,
                            Nome = "João Colaborador"
                        });
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnergisaNotes.Domain.Entities.Usuario", "UltimoEditor")
                        .WithMany()
                        .HasForeignKey("UltimoEditorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("UltimoEditor");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("EnergisaNotes.Domain.Entities.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("EnergisaNotes.Domain.Entities.Area", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
